# Generated by Django 2.0.5 on 2018-09-11 23:42

from django.db import migrations

def seed(apps, schema_editor):
    User = apps.get_model('project1dmr', 'User')
    Post = apps.get_model('project1dmr', 'Post')
    Comment = apps.get_model('project1dmr', 'Comment')

    userA = User(email = "a@a.com", password = "a")
    userA.save()

    post1 = Post(user = userA, stock_name = "aapl", post = "Apple is doing good, you should buy it.", image_url = "https://i.imgur.com/us8mMrI.png")
    post1.save()

    comment1 = Comment(user = userA, post = post1, comment = "Agree, buy more.")
    comment1.save()
    comment2 = Comment(user = userA, post = post1, comment = "iPhone still has problem.")
    comment2.save()

def fallow(apps, schema_editor):
    User = apps.get_model('project1dmr', 'User')
    Post = apps.get_model('project1dmr', 'Post')
    Comment = apps.get_model('project1dmr', 'Comment')
    User.objects.all().delete()
    Post.objects.all().delete()
    Comment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('project1dmr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
